apiVersion: v1
kind: Service
metadata:
  name: iconrepo-nodejs
  labels:
    app: iconrepo-nodejs
spec:
  selector:
    app: iconrepo-nodejs
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iconrepo-nodejs
  name: iconrepo-nodejs
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iconrepo-nodejs
  template:
    metadata:
      labels:
        app: iconrepo-nodejs
    spec:
      containers:
      - image: iconrepo-nodejs:latest
        imagePullPolicy: Never
        name: iconrepo-nodejs
        env:
        - name: LOG_LEVEL
          value: debug
        - name: ICONREPO_CONFIG_FILE
          value: /etc/config/config.json
        - name: OIDC_CLIENT_SECRET
          valueFrom:
           secretKeyRef:
             name: iconrepo-nodejs
             key: OIDC_CLIENT_SECRET
        - name: GITLAB_ACCESS_TOKEN
          valueFrom:
           secretKeyRef:
             name: iconrepo-nodejs
             key: GITLAB_ACCESS_TOKEN
        - name: DYNAMODB_URL
          value: http://dynamodb:8000 # local
          # value: "-" # the "real" aws service
          # value: "" # Use postgres for indexing (instead of dynamodb)
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
           secretKeyRef:
             name: iconrepo-nodejs
             key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
           secretKeyRef:
             name: iconrepo-nodejs
             key: AWS_SECRET_ACCESS_KEY
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /app-info
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: iconrepo-nodejs
        - name: secrets-volume
          